### ISSUE TITLE
Problème d'installation des tables

### ISSUE THREAD

**Issue by gplanchat** [wootook/wootook#4]
Ref: http://wootook.org/board/index.php/topic,3158.0.html

voila j'ai attendu longtemps la sorti de wootook mais il y a dejades erreurs a l'installation :P
(les erreurs surviennent lors de la page ?mode=install&step=3)

premiere erreur:

```
Message #1

    Uncaught Exception: Invalid version stage.
    #0 C:\wamp\www\install\index.php(467): Wootook_Core_ErrorProfiler->exceptionManager(Object(Wootook_Core_Setup_Exception_VersionStageError))
    #1 {main}

Message #1, child level #1

    Invalid version stage.
    #0 C:\wamp\www\application\code\core\Wootook\Core\Setup\Updater\ScriptQueue.php(204): Wootook_Core_Setup_Updater_ScriptQueue->_installHighestInstaller(Array, Array)
    #1 C:\wamp\www\application\code\core\Wootook\Core\Setup\Updater\ScriptQueue.php(70): Wootook_Core_Setup_Updater_ScriptQueue->_upgradeToVersion(Array, Array)
    #2 C:\wamp\www\install\index.php(460): Wootook_Core_Setup_Updater_ScriptQueue->__construct('C:\wamp\www\app...', NULL, '1.5.0')
    #3 {main}
```

et deuxième erreurs

```
Message #2

    Uncaught Exception: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'small_protection_shield'
    #0 [internal function]: Wootook_Core_ErrorProfiler->exceptionManager(Object(Wootook_Core_Exception_Database_StatementError))
    #1 {main}

Message #2, child level #1

    SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'small_protection_shield'
    #0 C:\wamp\www\application\code\core\Wootook\Core\Database\Adapter\Adapter.php(138): Wootook_Core_Database_Statement_Pdo_Mysql->execute()
    #1 C:\wamp\www\application\code\core\Wootook\Core\Setup\Updater.php(46): Wootook_Core_Database_Adapter_Adapter->query('CREATE TABLE IF...')
    #2 C:\wamp\www\application\code\core\Legacies\Empire\install\mysql5\install-1.5.0.php(369): Wootook_Core_Setup_Updater->query('CREATE TABLE IF...')
    #3 C:\wamp\www\application\code\core\Wootook\Core\Setup\Updater.php(107): include('C:\wamp\www\app...')
    #4 C:\wamp\www\install\index.php(463): Wootook_Core_Setup_Updater->run('C:\wamp\www\app...')
    #5 {main}


Message #2, child level #2

    SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'small_protection_shield'
    #0 C:\wamp\www\application\code\core\Wootook\Core\Database\Statement\Pdo\Mysql.php(100): PDOStatement->execute(NULL)
    #1 C:\wamp\www\application\code\core\Wootook\Core\Database\Adapter\Adapter.php(138): Wootook_Core_Database_Statement_Pdo_Mysql->execute()
    #2 C:\wamp\www\application\code\core\Wootook\Core\Setup\Updater.php(46): Wootook_Core_Database_Adapter_Adapter->query('CREATE TABLE IF...')
    #3 C:\wamp\www\application\code\core\Legacies\Empire\install\mysql5\install-1.5.0.php(369): Wootook_Core_Setup_Updater->query('CREATE TABLE IF...')
    #4 C:\wamp\www\application\code\core\Wootook\Core\Setup\Updater.php(107): include('C:\wamp\www\app...')
    #5 C:\wamp\www\install\index.php(463): Wootook_Core_Setup_Updater->run('C:\wamp\www\app...')
    #6 {main}
```

**Comment by ghost** [comment]
il suffit d'aller dans:

```
C:\wamp\www\application\code\core\Legacies\Empire\install\mysql5
```

dans le fichier install-1.5.0.php:
(ligne  354 à 355 )

remplacer ceci:
Code:

```
`small_protection_shield`       ENUM('0','1')           NOT NULL    DEFAULT 0,
`big_protection_shield`         ENUM('0','1')           NOT NULL    DEFAULT 0,
```

par cela:

Code:

```
`small_protection_shield`       ENUM('0','1')           NOT NULL    DEFAULT '0',
`big_protection_shield`         ENUM('0','1')           NOT NULL    DEFAULT '0',
```

maintenant c'est un probleme de redirection :)

code source de la page localhost:
Code: [Sélectionner]

<span class="logout"><a href="http://localhost/player/account/logout/">Logout</a></span>
    <span class="back"><a href="http://localhost/player/overview/">Back to the game</a></span>
